---
title: "Homework11"
author: "LaurenBomeisl"
date: "5/09/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#prelims
library(ggplot2)
library(TeachingDemos)
#set seed for recreatable results
char2seed("P loss")

#global variables
nVal<-20
applied<-runif(nVal,5,8)  # total p applied to calculate inefficiency

# Read in functions

#############################################
# function: readData
# read in or generate data frame
# input: file name (or nothing for demo)
# output: 3-column data frame of observed data (ID, x, y)

readData <- function(z=NULL){
  if(is.null(z)) {
    xVar <- runif(nVal,2,5) #identify the x variable as P consumed
    yVar <- (applied-xVar)/applied #calculate p inefficiency
    
    dF <- data.frame(ID=seq_along
                     (xVar), xVar, yVar)} #close if statement
    
    return(dF)

  } #close compound statement



    ##############################
    # function: getMetric
    # calculate metric for randomization test
    # input: 3-column data frame for regression
  
    getMetric <- function(dframe=NULL){
        
      . <- lm(dframe[,3]~dframe[,2])
      . <- summary(.)
      . <- .$coefficients[2,1]
      slope <- .
      return(slope)
      
    }   #close compound statement

  ################################################
    # function: shuffleData
    # randomize data for regression anlysis
    # input: 3 column data frame (id, x, y)
    # output: 3 column data frame (id, x, y)
    
    shuffleData <- function(dframe=NULL){

      dframe[,3] <- sample(dframe[,3])
      return(dframe)
      
    }   #close compound statement


      #################################################
    # function: getPVAL
    # calculate p value for observed, simulated data
    # input: list of observed metric and vector of simulated metric
    # output: lower, upper tail probability vector
    # --------------------------------------------
    
    
    getPval <- function(z=NULL) {
            if(is.null(z)){
              z <- list(xObs=runif(1),xSim=runif(1000))}
      
      pLower <- mean(z[[2]] <=z[[1]])
      pUpper <- mean(z[[2]] >=z[[1]])
                     # double bracket operation identifies actual values, not rows or columns
                     
    return(c(pL=pLower,pU=pUpper))
      
    } 
    

    

```



```{r}

    readData()
        getMetric(readData())
              shuffleData(readData())

    t.test(readData())  # p value for data created
    t.test(shuffleData(readData()))  # p value for shuffled data
    
    # In comparison, there was little difference between the p val -- each had the same     order of magnitude

```





